### ISSUE TITLE
what is Serial1 ?

### ISSUE THREAD

**Issue by oofin008** [ArduCreate2/Create2-Library#6]
The library can not compile it said that Serial1 was not declared in this scope

**Comment by ArduCreate2** [comment]
What Arduino board are you using? 'Serial1' is specific to the Arduino Mega. If you are using a different Arduino, you can change the code in the example scripts to use 'Serial' rather than 'Serial1'. 

However, if you choose to use the standard 'Serial' RX/TX, then review the following document:
https://www.irobotweb.com/-/media/MainSite/PDFs/About/STEM/Create/Arduino_Tutorial.pdf
